### ISSUE TITLE
Warnings du package hyperref

### ISSUE THREAD

**Issue by AKielhorn** [maieul/latexhumain#14]
Bonjour!

I hope you don't mind if i write in english, my french is rather limited.

There are several cases of

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\delimiter' on input line 79.

or similar.

This can be corrected with \texorpdfstring{}{} as shown in the examples below.
The first is just to keep TeX quiet, the second creates incorrect PDF bookmarks.
(There are more cases, I just picked these two.)

Should I fork and submit a pull request or is this issue sufficient?

citation.tex:
\section[Appel du package]{Appel du package \package{biblatex}}

\section[Appel du package]{\texorpdfstring{Appel du package \package{biblatex}}{Appel du package biblatex}}

\subsection{Les arguments \arg{prenote} et \arg{postnote}}

\subsection{\texorpdfstring{Les arguments \arg{prenote} et \arg{postnote}}{Les arguments prenote et postnote}}

Axel

**Comment by maieul** [comment]
hi, some news?

**Comment by maieul** [comment]
I close this issue. Reopen if needed.
