### ISSUE TITLE
Newcommand

### ISSUE THREAD

**Issue by Loumiel** [maieul/latexhumain#34]
Tu dis page 54 qu'il est compliqué de créer des nouvelles commandes avec argument optionnel et qu'il faut un autre package. La commande de base \newcommand permet de le faire mais juste pour le premier argument qui peut être optionnel, il faudrait peut être l'indiquer.

**Comment by maieul** [comment]
il faut que je trouve un exemple qui soit assez intéressant pour faire une étude de cas. Idée : commande pour afficher en option date d'un auteur après son nom.

**Comment by Loumiel** [comment]
J'utilise beaucoup les arguments optionnels mais j'ai n'ai pas le même métier. Je l'utilise surtout quand la valeur de l'argument est la même dans 90% des cas, n'ayant ainsi à entrer une valeur que pour les 10% restants. Par exemple j'ai une commande "\trou" pour afficher des points surlequels les élèves répondent. La taille standard est pour un nombre, si j'indique une autre valeur c'est qu'il faut que mes pointillés soient plus long.

**Comment by maieul** [comment]
oui, je vois, je fais la même chose pour d'autres besoins. Mais dans le cas présent il faut que je reste sur des exemples simples et correspondant à l'ensemble du livre...=

**Comment by Loumiel** [comment]
Pour un livre sur un livre donné, par défaut son titre apparait et si un autre est cité on utilise l'argument optionnel ?

**Comment by maieul** [comment]
pas compris … non mais je crois que le système de mettre entre parenthèse la date d'un auteur est pas mal, c'est assez simple et cela correspond au premier exemple=
