### ISSUE TITLE
Undefined control sequence: \@currentHref

### ISSUE THREAD

**Issue by bk** [maieul/latexhumain#49]
I am using Debian 8.0 and TeXLive 2014. I installed reledmac and indextools manually using tlmgr. When I type `make` after cloning the repository I get the error

```
! Undefined control sequence.
<argument> \@currentHref

l.32     \end{longtable}

?

! Emergency stop.
<argument> \@currentHref 

l.32     \end{longtable}
```

when making the `ecran.pdf` file. There are also many warnings about undefined references. I am attaching the [ecran.log file](https://github.com/maieul/latexhumain/files/177635/ecran.log.txt) to this issue, in case that clarifies the problem.

By the way, I think you should add installation of reledmac and indextools to the "Pour compiler" section of the README.

**Comment by maieul** [comment]
No, I suppose you have a updated texlive. I won't tell people to do that� 

But why don't you dowload the compiled pdffile on ctan ?

**Comment by maieul** [comment]
With updated texlive2015, all is working. i close this issue.
