### ISSUE TITLE
Ajouts de texte et suggestions

### ISSUE THREAD

**Issue by AlainDe** [maieul/latexhumain#84]
page 19 : Dans votre éditeur de texte, frappez le code suivant**, sauvegarder le en .tex,** puis cliquez sur le bouton de compilation avec XELATEX
page 31 ligne 5 : Le ﬁchier « père » doit systématiquement commencer par un appel de classe **et le préambule éventuel**, et contenir \begin{document} et \end{document}.
page 31 ligne 3 en bas : Il est déconseillé d’avoir des caractères spéciaux**, accentués et des espaces** dans le nom des dossiers et des ﬁchiers.

page 21 : \usepackage{xunicode}    est-ce encore nécessaire ?

éventuellement, mettre en gras ou italique les mots nouveaux introduits, comme " préambule " page 22 bas, " environnement " page 26 milieu,...

**Comment by maieul** [comment]
p. 19 et 31 l. 3 depuis le bas : pris en compte avec d'autres formulations (0735c84ed4cc6e19cdbd968c2d1f22a783622b47 et 881e4c2919a7222d7550fbe834ab5e955e66bd49)

p. 21: oui, plus besoin de xunicode qui est appelé si nécessaire par fontspec. C'est déjà corrigé pour la prochaine éditiom.

p. 31 l. 5 : c'est plus compliqué. On va voir avec #85
