### ISSUE TITLE
Mélange français-espagnol

### ISSUE THREAD

**Issue by B-Gaudeul** [maieul/latexhumain#88]

**Comment by maieul** [comment]
Mais encore ?

**Comment by B-Gaudeul** [comment]
J'ai l'impression que comme le suggère le dernier commit sur master de nombreux fichiers ont été remplacés par leur traduction en espagnol.

> Cher Maieul :
>J'ai fait une grave erreur : ce matin j'ai chargé quelques fichiers de la traduction espagnole et je me suis rendu compte >que j'avais modifié la branche principale, au lieu de la traduction. Pourriez-vous récupérer la version originale française ?
>Merci beaucoup et désolé pour la catastrophe, mais je ne me débrouille pas très bien avec GitHub.
>Manuel González

J'imagine qu'il faut reset au commit 927eef50a4b464dd63d87443797b005a00d153b1

**Comment by maieul** [comment]
Ah oui tiens... je ne l'avais pas vu passé vu que c'état dans un message de commit. Bon je vais m'occuper de cela.

**Comment by B-Gaudeul** [comment]
Merci beaucoup!

**Comment by maieul** [comment]
voilà, c'est fait, et j'ai protégé la branche master pour que cela n'arrive plus

@ManuelGonzalezSuarezOviedo  -> normalement j'ai mis tout vos commits erronnés dans la branche espagnol

**Comment by B-Gaudeul** [comment]
Super mille mercis! plus qu'à regler mon problème de biber et j'ai hate de lire cette version màj :-)

**Comment by maieul** [comment]
je ne crois pas qu'il y ait eu helas beaucoup de maj depuis la sortie publique...
